INFO:core:POX 0.2.0 (carp) is up.
INFO:openflow.of_01:[00-00-00-00-00-08 6] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[62-99-7e-56-45-43 1] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-02 10] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-07 11] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-06 5] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-07 9] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-04 4] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[f2-93-c6-cb-ba-4a 7] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[c2-85-43-f5-69-44 3] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-07 8] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-05 2] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-02 17] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-03 14] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-06 13] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-06 16] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-02 15] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-02 12] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-04 19] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-08 18] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:openflow.of_01:[00-00-00-00-00-03 20] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-07 30] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-08 29] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-09 21] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-09 26] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-05 25] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-03 27] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-06 23] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-03 22] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-09 24] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-01 28] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[7a-5d-df-ce-52-44 31] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-05 32] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-09 34] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-01 36] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-01 35] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-08 33] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:openflow.of_01:[00-00-00-00-00-04 38] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-01 37] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:openflow.of_01:[00-00-00-00-00-04 39] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:openflow.of_01:[00-00-00-00-00-05 40] connected
ERROR:core:Exception while handling OpenFlowNexus!ConnectionUp...
Traceback (most recent call last):
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 231, in raiseEventNoErrors
    return self.raiseEvent(event, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 278, in raiseEvent
    rv = event._invoke(handler, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/lib/revent/revent.py", line 156, in _invoke
    return handler(self, *args, **kw)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 257, in start_switch
    Tutorial(event.connection)
  File "/home/emmadauterman/cs244project2/poxStartup/pox/pox/ext/jelly_controller.py", line 52, in __init__
    with open('generated_rrg', 'r') as infile:
IOError: [Errno 2] No such file or directory: 'generated_rrg'
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
INFO:jelly_controller:packet in
